# Generated by Django 3.1.2 on 2020-10-04 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_pickup'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickup',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
