# Generated by Django 3.1.2 on 2020-10-04 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_pickup_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='pay_on_delivery',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
