# Generated by Django 3.0.8 on 2020-07-22 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_billingdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.BillingDetails'),
        ),
    ]
