# Generated by Django 3.1.2 on 2021-03-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20210316_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image_mobi_770x331',
            field=models.ImageField(default='No_image_available.png', upload_to='cat_imgs'),
        ),
    ]
