# Generated by Django 2.2.16 on 2020-09-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image1920x80', models.ImageField(upload_to='ad_imgs')),
                ('discount_offer', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(max_length=200)),
                ('description2', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
