# Generated by Django 3.1.2 on 2020-10-06 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20201006_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotionimg',
            old_name='image_379x188',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='slider',
            old_name='image_1920x358',
            new_name='image',
        ),
    ]
